### ISSUE TITLE
Add Own Logo

### ISSUE THREAD

**Issue by VariousGames** [steeviebops/hacktv-gui#9]
hey  all

Quick question: 

I have just starded with this software, it works perfect on an old Bulp TV (Aristona 42KT2162/23S)

is there a way to add own logo to the software?
and edit the Size and location of it?
im using the software on Windows 10

**Comment by steeviebops** [comment]
Not through the GUI directly, that needs to be done in the hacktv source itself.

https://github.com/captainjack64/hacktv/blob/master/src/graphics.c
https://github.com/captainjack64/hacktv/blob/master/src/resources.h

graphics.c contains the list of logos, while resources.h contains the logos themselves in PNG format, albeit hex encoded. I normally use the free HxD hex editor to get the files in the correct format, as follows:

Open the PNG file in HxD but don't make any changes to it. Go to the Tools menu, choose Options and go to the Export tab. Make sure that the "Bytes per line" option is selected, and set it to 32. Click OK, then go to File > Export > C. Save that file and it'll be in the correct format for the resources.h file.

Once that's done, you'll need to edit captainjack.ini in the GUI from the address below. Add your logo to the [logos] section and save the file in the same location as hacktv-gui.jar:

https://raw.githubusercontent.com/steeviebops/hacktv-gui/main/src/com/steeviebops/resources/captainjack.ini

**Comment by VariousGames** [comment]
aah oke i go try it :D
